workflows:
  ios-app:
    name: Build iOS App
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "McDonald's.xcodeproj"
        XCODE_SCHEME: "McDonald's"
    scripts:
      - name: Set up project
        script: |
          echo "Using project: $XCODE_PROJECT"
          echo "Using scheme: $XCODE_SCHEME"
      - name: Build .ipa
        script: |
          xcodebuild clean -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -sdk iphoneos -configuration Release
          xcodebuild archive -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -archivePath build/"$XCODE_SCHEME".xcarchive
          xcodebuild -exportArchive -archivePath build/"$XCODE_SCHEME".xcarchive -exportPath build/export -exportOptionsPlist exportOptions.plist
    artifacts:
      - build/export/*.ipa